### ISSUE TITLE
Does not work on pip 10

### ISSUE THREAD

**Issue by singularitti** [balzss/yip#8]
When I am trying to type `yip <some package>`, it returns me some messages
```shell
 |----------------------------------------------------------------------------------------------------| 0.0% Traceback (most recent call last):
  File "/usr/local/bin/yip", line 434, in <module>
    installed_packages = get_installed()
  File "/usr/local/bin/yip", line 152, in get_installed
    return {i.key: i.version for i in pip.get_installed_distributions()}
AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```
It seems that it does not work on pip 10 and above. It could probably be solved by `from pip._internal.utils.misc import get_installed_distributions` instead of `pip.get_installed_distributions` directly. 
My pip version:

```shell
$ pip3 -V
pip 10.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

Reference
1. https://github.com/pypa/pip/issues/5243

**Comment by singularitti** [comment]
I am sorry I misunderstood the [discussion here](https://github.com/pypa/pip/issues/5243).
We are not allowed to import from `pip` based on [official document](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program), rather we should use some other packages to solve this problem. For example, `pkg_resources` or `subprocess`.
In pull request #9, I deprecate `pip` and fix a bug in existing code.

**Comment by balzss** [comment]
Hi, thanks for filing this issue and the pull request. I'll go through your changes as soon as I'll have some time and merge it.

**Comment by singularitti** [comment]
Just curious about is this bug is fixed?

**Comment by totedati** [comment]
No, is not fixed. Yip still use pip get_installed_distributions private api:

`source .venv/bin/activate
python -m pip install --upgrade pip

pip -V
pip 21.1.2 from /home/totedati/.venv/lib/python3.8/site-packages/pip (python 3.8)

python -m pip install --upgrade yip

yip ffmpeg -s
 |----------------------------------------------------------------------------------------------------| 0.0% Traceback (most recent call last):
  File "/home/totedati/.venv/bin/yip", line 434, in <module>
    installed_packages = get_installed()
  File "/home/totedati/.venv/bin/yip", line 152, in get_installed
    return {i.key: i.version for i in pip.get_installed_distributions()}
AttributeError: module 'pip' has no attribute 'get_installed_distributions'`

and the only real solution is to downgrade pip version below v9.0.3 when you want to use yip instead of "pip search"
